/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUILoanPackage;

import java.util.ArrayList;
import java.util.InputMismatchException;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rextine
 */
public class LoanApplication extends javax.swing.JFrame implements LoanConstants{
    static ArrayList <Loan> loans = new ArrayList<>();
    Loan loan = null;
    
    public LoanApplication() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        compName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        lastNameTxt = new javax.swing.JTextField();
        loanNumberTxt = new javax.swing.JTextField();
        loanAmtTxt = new javax.swing.JTextField();
        termTypeOption = new javax.swing.JComboBox<>();
        displayBtn = new javax.swing.JButton();
        clearBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        viewLoansOption = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayField = new javax.swing.JTextArea();
        loanTypeOption = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        searchLoanNumTxt = new javax.swing.JTextField();
        primeRateTxt = new javax.swing.JTextField();
        interestTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Loan Number");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Last Name");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Amount to Loan");

        compName.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        compName.setForeground(new java.awt.Color(0, 0, 0));
        compName.setText("SANCHEZ CONSTRUCTION LOAN CO");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Interest Rate");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Term");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        lastNameTxt.setBackground(new java.awt.Color(255, 255, 255));
        lastNameTxt.setForeground(new java.awt.Color(0, 0, 0));

        loanNumberTxt.setBackground(new java.awt.Color(255, 255, 255));
        loanNumberTxt.setForeground(new java.awt.Color(0, 0, 0));

        loanAmtTxt.setBackground(new java.awt.Color(255, 255, 255));
        loanAmtTxt.setForeground(new java.awt.Color(0, 0, 0));
        loanAmtTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loanAmtTxtActionPerformed(evt);
            }
        });

        termTypeOption.setBackground(new java.awt.Color(255, 255, 255));
        termTypeOption.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        termTypeOption.setForeground(new java.awt.Color(0, 0, 0));
        termTypeOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Choose Term Type", "Short Term", "Medium Term", "Long Term"}));

        displayBtn.setText("Display");
        displayBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBtnActionPerformed(evt);
            }
        });

        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        exitBtn.setText("Exit");
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("What do you want to view?");

        viewLoansOption.setBackground(new java.awt.Color(255, 255, 255));
        viewLoansOption.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        viewLoansOption.setForeground(new java.awt.Color(0, 0, 0));
        viewLoansOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Option", "All Loan", "Business Loan", "Personal Loan" }));
        viewLoansOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewLoansOptionActionPerformed(evt);
            }
        });

        displayField.setBackground(new java.awt.Color(255, 255, 255));
        displayField.setColumns(20);
        displayField.setRows(5);
        jScrollPane1.setViewportView(displayField);

        loanTypeOption.setBackground(new java.awt.Color(255, 255, 255));
        loanTypeOption.setEditable(true);
        loanTypeOption.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loanTypeOption.setForeground(new java.awt.Color(0, 0, 0));
        loanTypeOption.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose Loan Type", "Business Loan", "Personal Loan" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Search Loan Number");

        searchLoanNumTxt.setBackground(new java.awt.Color(255, 255, 255));
        searchLoanNumTxt.setForeground(new java.awt.Color(0, 0, 0));
        searchLoanNumTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchLoanNumTxtActionPerformed(evt);
            }
        });

        primeRateTxt.setBackground(new java.awt.Color(255, 255, 255));
        primeRateTxt.setForeground(new java.awt.Color(0, 0, 0));

        interestTxt.setBackground(new java.awt.Color(255, 255, 255));
        interestTxt.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Prime Interest Rate");

        searchBtn.setBackground(new java.awt.Color(255, 255, 255));
        searchBtn.setForeground(new java.awt.Color(0, 0, 0));
        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(saveBtn)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(14, 14, 14)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(clearBtn)
                                .addGap(53, 53, 53)
                                .addComponent(displayBtn)
                                .addGap(45, 45, 45)
                                .addComponent(exitBtn))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(interestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addComponent(compName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel9)
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loanAmtTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(loanNumberTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                            .addComponent(termTypeOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(loanTypeOption, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(primeRateTxt))
                        .addGap(477, 477, 477)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewLoansOption, 0, 157, Short.MAX_VALUE)
                                    .addComponent(searchLoanNumTxt))
                                .addGap(18, 18, 18)
                                .addComponent(searchBtn)))))
                .addContainerGap(228, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(compName, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(loanNumberTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(viewLoansOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(searchLoanNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(loanAmtTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(termTypeOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(loanTypeOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(primeRateTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(interestTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn)
                    .addComponent(clearBtn)
                    .addComponent(displayBtn)
                    .addComponent(exitBtn))
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int term;
        
        if (primeRateTxt.getText().isEmpty() && loanNumberTxt.getText().isEmpty() && lastNameTxt.getText().isEmpty() &&
            loanAmtTxt.getText().isEmpty() && loanTypeOption.getSelectedIndex() == 0 && termTypeOption.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Please fill out all required fields.");
            return;
        }
             
        try{
            int primeInterestRate = Integer.parseInt(primeRateTxt.getText());
            int loanNum = Integer.parseInt(loanNumberTxt.getText());
            String lastName = lastNameTxt.getText();
            float loanAmt = Float.parseFloat(loanAmtTxt.getText());
            String loanType = (String) loanTypeOption.getSelectedItem();
            String termType = (String) termTypeOption.getSelectedItem();
            
            
            if(primeRateTxt.getText().isEmpty() || loanNumberTxt.getText().isEmpty() || lastNameTxt.getText().isEmpty() || loanAmtTxt.getText().isEmpty() ||
            loanType.isEmpty() || termType.isEmpty()){
                JOptionPane.showMessageDialog(this, "Please fill out all required fields.");
                return;
            }
            
            if(lastName.matches(".*\\d.*")){
                JOptionPane.showMessageDialog(this, "Invalid input.\n");
                return;
            }
            
            if(loanAmt > MAX_LOAN_AMOUNT){
                JOptionPane.showMessageDialog(this, "Loan amount cannot exceed $100,000\n");
                return;
            }
            
            boolean checkLoan = false;
            for(int i = 0; i < loans.size(); i++){
                if(loans.get(i).getLoanNum() == loanNum){ 
                    checkLoan = true;
                    break;
                }
            }
            
        if(checkLoan){
            clearBtnActionPerformed(evt);
            JOptionPane.showMessageDialog(this, "Loan number already exist.\n");
        }else{
                switch (termType) {
                    case "Short Term":
                        term = SHORT_TERM;
                        break;
                    case "Medium Term":
                        term = MEDIUM_TERM;
                        break;
                    case "Long Term":
                        term = LONG_TERM;
                        break;
                    default:
                        JOptionPane.showMessageDialog(this, "Please select a term type.\n");
                        return;
                }
            
            switch(loanType){
                case "Business Loan":
                    loan = new BusinessLoan(loanNum, lastName, loanAmt, term, primeInterestRate);
                    interestTxt.setText("1");
                    loans.add(loan);
                    break;
                case "Personal Loan":
                    loan = new PersonalLoan(loanNum, lastName, loanAmt, term, primeInterestRate);
                    loan.setInterestRate(primeInterestRate);
                    interestTxt.setText("2");
                    loans.add(loan);
                    break;
                default:
                    JOptionPane.showMessageDialog(this, "Please select a loan type.");
                    return; 
                    
            }
            JOptionPane.showMessageDialog(this, "Information Saved.\n");
            clearBtnActionPerformed(evt);
            primeRateTxt.setEditable(false);
            interestTxt.setEditable(false);
            }
        }catch(InputMismatchException | NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Invalid input.\n");
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void displayBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBtnActionPerformed
        StringBuilder displayLoan = new StringBuilder();
        
        if(loans.isEmpty()){
            JOptionPane.showMessageDialog(this, "No loans to display. Please add loans first.\n");
        }else{
            for(int i = 0; i < loans.size(); i++){
                if(loans.get(i) instanceof BusinessLoan){
                    displayLoan.append("Business Loan\n").append(loans.get(i).toString()).append("\n\n");
                }else if(loans.get(i) instanceof PersonalLoan){
                    displayLoan.append("Personal Loan\n").append(loans.get(i).toString()).append("\n\n");
                }
            }
       }
        displayField.setText(displayLoan.toString());
    }//GEN-LAST:event_displayBtnActionPerformed
    
    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        loanNumberTxt.setText(null);
        lastNameTxt.setText(null);
        loanAmtTxt.setText(null);
        interestTxt.setText(null);
        termTypeOption.setSelectedIndex(0);
        loanTypeOption.setSelectedIndex(0);
    }//GEN-LAST:event_clearBtnActionPerformed

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitBtnActionPerformed

    private void loanAmtTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loanAmtTxtActionPerformed

    }//GEN-LAST:event_loanAmtTxtActionPerformed

    private void viewLoansOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewLoansOptionActionPerformed
        StringBuilder loanField = new StringBuilder();
        String select = (String) viewLoansOption.getSelectedItem();
        
        if(loans.isEmpty()){
           JOptionPane.showMessageDialog(this, "No loans to display. Please add loans first.\n");
       }else{
        switch(select){
            case "All Loan":   
                for(int i = 0; i < loans.size(); i++){
                    if(loans.get(i) instanceof BusinessLoan){
                        loanField.append("Business Loan\n").append(loans.get(i).toString()).append("\n\n");
                    }else if(loans.get(i) instanceof PersonalLoan){
                        loanField.append("Personal Loan\n").append(loans.get(i).toString()).append("\n\n");
                    }
                }
                break;
            case "Business Loan":
                for (int i = 0; i < loans.size(); i++) {
                    if (loans.get(i) instanceof BusinessLoan) {
                        loanField.append(loans.get(i).toString()).append("\n");
                    }
                }
            break;
            case "Personal Loan":
                for (int i = 0; i < loans.size(); i++) {
                    if (loans.get(i) instanceof PersonalLoan) {
                        loanField.append(loans.get(i).toString()).append("\n");
                    }
                }
            break;
            }
        }
        displayField.setText(loanField.toString());
    }//GEN-LAST:event_viewLoansOptionActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        StringBuilder searchResult = new StringBuilder();
       
        if(searchLoanNumTxt.getText().isEmpty() && loans.isEmpty()){
            JOptionPane.showMessageDialog(this, "No loans to display. Please add loans first.");
            return;
        }else if(searchLoanNumTxt.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Please enter a loan number.");
            return;
        }else if(loans.isEmpty()){
            JOptionPane.showMessageDialog(this, "No loans to display. Please add loans first.");
            return;
        }
       
        
        try{
            int searchLoanNum = Integer.parseInt(searchLoanNumTxt.getText());
            
            boolean found = false;
                for(int i = 0; i < loans.size(); i++){
                    if(loans.get(i).getLoanNum() == searchLoanNum) {
                        if(loans.get(i) instanceof BusinessLoan){
                            searchResult.append("Business Loan\n").append(loans.get(i).toString()).append("\n\n");
                        }else if(loans.get(i) instanceof PersonalLoan){
                            searchResult.append("Personal Loan\n").append(loans.get(i).toString()).append("\n\n");
                        }
                        found = true;
                        break;
                    }
                }
                
                if(!found){
                    JOptionPane.showMessageDialog(this, "Loan not found.\n");
                    return;
                }
            displayField.setText(searchResult.toString());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(this, "Please enter a valid loan number\n");
        }
        
    }//GEN-LAST:event_searchBtnActionPerformed

    private void searchLoanNumTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchLoanNumTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchLoanNumTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoanApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoanApplication().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearBtn;
    private javax.swing.JLabel compName;
    private javax.swing.JButton displayBtn;
    private javax.swing.JTextArea displayField;
    private javax.swing.JButton exitBtn;
    private javax.swing.JTextField interestTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastNameTxt;
    private javax.swing.JTextField loanAmtTxt;
    private javax.swing.JTextField loanNumberTxt;
    private javax.swing.JComboBox<String> loanTypeOption;
    private javax.swing.JTextField primeRateTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchLoanNumTxt;
    private javax.swing.JComboBox<String> termTypeOption;
    private javax.swing.JComboBox<String> viewLoansOption;
    // End of variables declaration//GEN-END:variables
}

